### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by PS3-Pro** [DADi590/Console-news-on-consoles#1]
Thanks for the nice work =)

Can you post the program or script that automatically generates the xml with the psx-place latest news?

**Comment by PS3-Pro** [comment]
Also,  there are some duplicated items, can it be fixed?

**Comment by Edw590** [comment]
Hi! Thanks! I just need to translate it to english and then I can publish it, yes.

The duplicate items are not actually duplicate. It happens when the title is changed, and it gets back to the first position, so people can notice there's an update. I've let that happen because of updates. See the GTA SA news, for example. The titles. They're different. "UPDATE" has been added to them. The description sometimes changes too. Yesterday one of them, the original had a description and the update had changed the description. That's why I let the "duplicates" stay - "Hey! There's an update here!".

**EDIT:** Not sure how I'd remove them though. I guess it'd be harder. I'd have to keep an unique ID of each news and where there was an update, I'd need to check if the ID was already in What's New, delete it and create a new one with the same ID but this time updated. Though, keep in mind that old descriptions and/or images will be lost, in case they're changed in the update.

**Comment by Edw590** [comment]
And it's posted. Here: https://github.com/DADi590/Console-news-on-consoles/blob/master/PSX_Place/PS3/whats_new_xml_creator.py. Hope it's not too confusing.

EDIT: Weird title you chose xD.
